"""empty message

Revision ID: dc29ffb64540
Revises: 9472d8b27a69
Create Date: 2025-07-22 20:43:54.690742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc29ffb64540'
down_revision = '9472d8b27a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disbursement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('record_number', sa.String(), nullable=True),
    sa.Column('po_number', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('ap_number', sa.String(), nullable=True),
    sa.Column('prepared_by', sa.String(), nullable=True),
    sa.Column('checked_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_disbursement',
    sa.Column('disbursement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disbursement_id'], ['disbursement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('disbursement_id', 'user_id')
    )
    op.create_table('disbursement_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disbursement_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['disbursement_id'], ['disbursement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_disbursement',
    sa.Column('disbursement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disbursement_id'], ['disbursement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('disbursement_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_disbursement')
    op.drop_table('disbursement_detail')
    op.drop_table('admin_disbursement')
    op.drop_table('disbursement')
    # ### end Alembic commands ###
